openapi: 3.0.0
info:
  title: To-Do API
  version: 1.0.0
  description: Simple express to-do-list API

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /toDos:
    get:
      summary: Returns the list of all the To-do items
      tags: 
        - To-do Items
      summary: Returns list of all the to-do items
      responses:
        200:
          description: JSON array of to-do items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  data:
                    - id: 62c550abbc503a0f6c0d7b29
                      toDoItem: Fix bugs
                      itemStatus: completed
                    - id: 64c550acbc503a0f6b0d7b29
                      toDoItem: Workout
                      itemStatus: active
                    - id: 63c550abc503a0n8e0d7b29
                      toDoItem: Check emails
                      itemStatus: active
  
  /create-toDo:
    post:
      tags: 
        - To-do Items
      summary: Create To-do item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "toDoItem"
              properties:
                toDoItem:
                  type: string
                  example: Go for a swim at the weekend
      responses: 
        201:
          description: Creates new To-do item successfully
          content: 
            application/json:
              schema: 
                type: object
              example:
                result: item created
        400:
          description: Bad request, invalid toDoItem
          content:
            application/json:
              schema:
                type: object
              example:
                errors: 
                  value: 123
                  msg: Invalid value
                  param: toDoItem
                  location: body
  
  /update-toDo:
    put:
      tags: 
        - To-do Items
      summary: Update To-do item's status
      requestBody:  
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - "id"
              properties:
                id:
                  type: string
                  example: 63c53421b0d8c6h1c9e38c53
      responses:
        200:
          description:  Updates items status successfully
          content:
            application/json:
              schema:
                type: object
              example: 
                result: item updated
        400:
          description: Incorrect id
          content:
            application/json:
              schema:
                type: object
              example:
                errors: 
                  value: 63c6bd91a402665be7da647
                  msg: Invalid value
                  param: id
                  location: body
  
  /delete-toDo:
    delete:
      tags:
        - To-do Items
      summary: Deletes single To-do item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - "id"
              properties:
                id: 
                  type: string
                  example: 63c6bd91a402665be7da6471
      responses:
        204:  
          description: Deletes item successfully
        400:
          description: Bad request, invalid id
          content:
            application/json:
              schema:
                type: object
              example:
                errors: 
                  value: 63c6bd91a402665be7da647
                  msg: Invalid value
                  param: id
                  location: body
  
  /delete-completed:
    delete:
      tags:
        - To-do Items
      summary: Deletes To-do items with completed status
      responses:
        204:  
          description: Deletes item successfully
        404:
          description: Bad request, invalid id
          content:
            application/json:
              schema:
                type: object
              example:
                errors: 
                  msg: No items found with completed status



